export const languages = {
  Latin: {
    styles: ["Classical", "Ecclesiastical", "Vulgar"],
    forms: ["Phonetic", "Phonemic"],
    langCode: "la",
    ttsCode: "it-IT",
  },
  German: {
    styles: ["Default"],
    forms: ["Phonemic", "Phonetic"],
    langCode: "de",
    ttsCode: "de-DE",
  },
  Portuguese: {
    styles: ["Brazil", "Portugal"],
    forms: ["Phonetic", "Phonemic"],
    langCode: "pt",
    ttsCode: "pt-BR",
  },
  Spanish: {
    styles: ["Castilian", "Latin_American "],
    forms: ["Phonetic", "Phonemic"],
    langCode: "es",
    ttsCode: "es-ES",
  },
  French: {
    styles: ["Default", "Parisian (experimental)"],
    forms: ["Phonemic"],
    langCode: "fr",
    ttsCode: "fr-FR",
  },
  Russian: {
    styles: ["Default"],
    forms: ["Phonetic"],
    langCode: "ru",
    ttsCode: "ru-RU",
  },
  Belorussian: {
    styles: ["Default"],
    forms: ["Phonemic"],
    langCode: "be",
    ttsCode: "be-BY",
  },
  Polish: {
    styles: ["Default"],
    forms: ["Phonemic"],
    langCode: "pl",
    ttsCode: "pl-PL",
  },
  Bulgarian: {
    styles: ["Default"],
    forms: ["Phonemic"],
    langCode: "bg",
    ttsCode: "bg-BG",
  },
  Ukrainian: {
    styles: ["Default"],
    forms: ["Phonetic"],
    langCode: "uk",
    ttsCode: "uk-UA",
  },
  Lithuanian: {
    styles: ["Default"],
    forms: ["Phonemic"],
    langCode: "lt",
    ttsCode: "lt-LT",
  },
  Czech: {
    styles: ["Default"],
    forms: ["Phonemic"],
    langCode: "cs",
    ttsCode: "cs-CZ",
  },
  Armenian: {
    styles: ["Western", "Eastern"],
    forms: ["Phonemic", "Phonetic"],
    langCode: "hy",
    ttsCode: "hy-AM",
  },
  Greek: {
    styles: [
      "5th BCE Attic",
      "1st CE Egyptian",
      "4th CE Koine",
      "10th CE Byzantine",
      "15th CE Constantinopolitan",
    ],
    forms: ["Phonemic"],
    langCode: "grc",
    ttsCode: "el-GR",
  },
  Icelandic: {
    styles: ["Default"],
    forms: ["Phonemic"],
    langCode: "is",
    ttsCode: "is-IS",
  },
  Mongolian: {
    styles: ["Default"],
    forms: ["Phonemic"],
    langCode: "mn",
    ttsCode: "mn-MN",
  },
};
export default { languages };
